services:
  glpi-mysql:
    image: elestio/mysql:9.1.0
    restart: always
    volumes:
      - glpi-mysql-data:/var/lib/mysql
    networks:
      - dokploy-network

  glpi-web:
    image: elestio/glpi:10.0.16
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - glpi-www-data:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Brussels
    networks:
      - dokploy-network

volumes:
  glpi-mysql-data:
  glpi-www-data:

networks:
  dokploy-network:
    external: true