version: "3.8"
services:
   appsmith:
     image: index.docker.io/appsmith/appsmith-ee:v1.29
     networks:
        - dokploy-network
     ports:
         - ${APP_SMITH_PORT}
     labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${HASH}.rule=Host(`${APP_SMITH_HOST}`)"
        - "traefik.http.services.${HASH}.loadbalancer.server.port=${APP_SMITH_PORT}"
     volumes:
         - ./stacks:/appsmith-stacks

networks:
  dokploy-network:
    external: true